name: "hello_world"
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build_runner:
  freezed_annotation:
  freezed:
  get_it:
  firebase_core: 2.30.1
  firebase_messaging: ^14.9.1
  device_info_plus:
  json_serializable:
  json_annotation:
  retrofit:
  retrofit_generator:
  cupertino_icons: ^1.0.2
  awesome_dialog:
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.1
  dio:
  bloc:
  flutter_bloc:
  smooth_page_indicator: ^1.0.0+2
  awesome_icons:
  image_picker:
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  progress_loading_button:
  carousel_slider:
  hideable_bottom_bar:
  flutter_localization:





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
